// Generated by covidm Thu May 20 12:22:50 2021

#include "user_defined.h"
#include "convenience.h"

void CppChanges(const vector<double>& x, Parameters& P)
{
    (void)x; (void)P;
    for (auto& u : P.pop[0].u) u *= x[1];
    for (auto& u : P.pop[0].uv) u *= x[1];
    P.pop[0].seed_times = vector<double>(10, (int)x[0]);
}

double CppLogLikelihood(const vector<double>& x, Reporter& dyn)
{
    (void)dyn;
    double ll = 0.0;
    { double d = dyn.Obs(120, 0, 1, 0) - 12; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(121, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(122, 0, 1, 0) - 4; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(123, 0, 1, 0) - 8; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(124, 0, 1, 0) - 7; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(125, 0, 1, 0) - 11; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(126, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(127, 0, 1, 0) - 14; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(128, 0, 1, 0) - 4; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(129, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(130, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(131, 0, 1, 0) - 11; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(132, 0, 1, 0) - 18; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(133, 0, 1, 0) - 16; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(134, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(135, 0, 1, 0) - 12; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(136, 0, 1, 0) - 13; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(137, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(138, 0, 1, 0) - 3; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(139, 0, 1, 0) - 19; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(140, 0, 1, 0) - 17; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(141, 0, 1, 0) - 20; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(142, 0, 1, 0) - 4; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(143, 0, 1, 0) - 14; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(144, 0, 1, 0) - 13; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(145, 0, 1, 0) - 2; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(146, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(147, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(148, 0, 1, 0) - 16; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(149, 0, 1, 0) - 31; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(150, 0, 1, 0) - 38; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(151, 0, 1, 0) - 16; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(152, 0, 1, 0) - 22; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(153, 0, 1, 0) - 23; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(154, 0, 1, 0) - 29; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(155, 0, 1, 0) - 20; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(156, 0, 1, 0) - 40; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(157, 0, 1, 0) - 19; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(158, 0, 1, 0) - 16; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(159, 0, 1, 0) - 29; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(160, 0, 1, 0) - 17; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(161, 0, 1, 0) - 42; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(162, 0, 1, 0) - 38; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(163, 0, 1, 0) - 17; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(164, 0, 1, 0) - 23; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(165, 0, 1, 0) - 15; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(166, 0, 1, 0) - 22; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(167, 0, 1, 0) - 33; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(168, 0, 1, 0) - 30; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(169, 0, 1, 0) - 48; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(170, 0, 1, 0) - 49; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(171, 0, 1, 0) - 35; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(172, 0, 1, 0) - 41; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(173, 0, 1, 0) - 14; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(174, 0, 1, 0) - 21; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(175, 0, 1, 0) - 37; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(176, 0, 1, 0) - 17; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(177, 0, 1, 0) - 27; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(178, 0, 1, 0) - 38; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(179, 0, 1, 0) - 45; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(180, 0, 1, 0) - 55; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(181, 0, 1, 0) - 34; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(182, 0, 1, 0) - 29; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(183, 0, 1, 0) - 31; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(184, 0, 1, 0) - 22; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(185, 0, 1, 0) - 42; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(186, 0, 1, 0) - 25; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(187, 0, 1, 0) - 46; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(188, 0, 1, 0) - 42; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(189, 0, 1, 0) - 23; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(190, 0, 1, 0) - 40; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(191, 0, 1, 0) - 36; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(192, 0, 1, 0) - 34; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(193, 0, 1, 0) - 48; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(194, 0, 1, 0) - 31; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(195, 0, 1, 0) - 37; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(196, 0, 1, 0) - 25; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(197, 0, 1, 0) - 34; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(198, 0, 1, 0) - 30; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(199, 0, 1, 0) - 22; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(200, 0, 1, 0) - 19; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(201, 0, 1, 0) - 26; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(202, 0, 1, 0) - 22; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(203, 0, 1, 0) - 19; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(204, 0, 1, 0) - 36; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(205, 0, 1, 0) - 14; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(206, 0, 1, 0) - 25; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(207, 0, 1, 0) - 16; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(208, 0, 1, 0) - 11; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(209, 0, 1, 0) - 10; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(210, 0, 1, 0) - 17; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(211, 0, 1, 0) - 20; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(212, 0, 1, 0) - 11; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(213, 0, 1, 0) - 3; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(214, 0, 1, 0) - 1; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(215, 0, 1, 0) - 2; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(216, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(217, 0, 1, 0) - 14; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(218, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(219, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(220, 0, 1, 0) - 3; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(221, 0, 1, 0) - 10; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(222, 0, 1, 0) - 10; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(223, 0, 1, 0) - 8; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(224, 0, 1, 0) - 7; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(225, 0, 1, 0) - 10; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(226, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(227, 0, 1, 0) - 4; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(228, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(229, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(230, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(231, 0, 1, 0) - 7; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(232, 0, 1, 0) - 7; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(233, 0, 1, 0) - 7; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(234, 0, 1, 0) - 1; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(235, 0, 1, 0) - 9; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(236, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(237, 0, 1, 0) - 11; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(238, 0, 1, 0) - 4; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(239, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(240, 0, 1, 0) - 1; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(241, 0, 1, 0) - 3; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(242, 0, 1, 0) - 3; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(243, 0, 1, 0) - 2; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(244, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(245, 0, 1, 0) - 6; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(246, 0, 1, 0) - 5; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(247, 0, 1, 0) - 2; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(248, 0, 1, 0) - 0; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(249, 0, 1, 0) - 1; ll += -0.5 * (d / x[2]) * (d / x[2]) - log(x[2] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(120, 0, 2, 0) - 358; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(121, 0, 2, 0) - 622; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(122, 0, 2, 0) - 427; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(123, 0, 2, 0) - 363; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(124, 0, 2, 0) - 417; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(125, 0, 2, 0) - 307; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(126, 0, 2, 0) - 451; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(127, 0, 2, 0) - 453; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(128, 0, 2, 0) - 598; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(129, 0, 2, 0) - 1080; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(130, 0, 2, 0) - 709; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(131, 0, 2, 0) - 537; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(132, 0, 2, 0) - 593; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(133, 0, 2, 0) - 731; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(134, 0, 2, 0) - 758; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(135, 0, 2, 0) - 817; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(136, 0, 2, 0) - 674; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(137, 0, 2, 0) - 787; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(138, 0, 2, 0) - 864; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(139, 0, 2, 0) - 706; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(140, 0, 2, 0) - 1017; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(141, 0, 2, 0) - 960; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(142, 0, 2, 0) - 959; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(143, 0, 2, 0) - 762; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(144, 0, 2, 0) - 846; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(145, 0, 2, 0) - 443; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(146, 0, 2, 0) - 573; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(147, 0, 2, 0) - 699; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(148, 0, 2, 0) - 1103; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(149, 0, 2, 0) - 804; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(150, 0, 2, 0) - 1247; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(151, 0, 2, 0) - 885; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(152, 0, 2, 0) - 1402; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(153, 0, 2, 0) - 1439; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(154, 0, 2, 0) - 783; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(155, 0, 2, 0) - 1667; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(156, 0, 2, 0) - 1353; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(157, 0, 2, 0) - 1475; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(158, 0, 2, 0) - 1744; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(159, 0, 2, 0) - 1447; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(160, 0, 2, 0) - 1748; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(161, 0, 2, 0) - 2487; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(162, 0, 2, 0) - 3038; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(163, 0, 2, 0) - 2428; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(164, 0, 2, 0) - 2262; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(165, 0, 2, 0) - 2287; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(166, 0, 2, 0) - 1776; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(167, 0, 2, 0) - 2287; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(168, 0, 2, 0) - 2115; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(169, 0, 2, 0) - 2286; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(170, 0, 2, 0) - 2894; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(171, 0, 2, 0) - 2190; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(172, 0, 2, 0) - 2275; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(173, 0, 2, 0) - 1464; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(174, 0, 2, 0) - 1564; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(175, 0, 2, 0) - 1414; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(176, 0, 2, 0) - 1098; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(177, 0, 2, 0) - 1150; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(178, 0, 2, 0) - 1949; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(179, 0, 2, 0) - 2179; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(180, 0, 2, 0) - 1539; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(181, 0, 2, 0) - 2655; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(182, 0, 2, 0) - 2155; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(183, 0, 2, 0) - 2430; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(184, 0, 2, 0) - 1496; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(185, 0, 2, 0) - 1585; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(186, 0, 2, 0) - 2222; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(187, 0, 2, 0) - 1708; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(188, 0, 2, 0) - 1390; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(189, 0, 2, 0) - 1736; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(190, 0, 2, 0) - 1538; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(191, 0, 2, 0) - 1468; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(192, 0, 2, 0) - 1452; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(193, 0, 2, 0) - 1713; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(194, 0, 2, 0) - 1089; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(195, 0, 2, 0) - 1151; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(196, 0, 2, 0) - 1140; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(197, 0, 2, 0) - 1155; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(198, 0, 2, 0) - 1170; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(199, 0, 2, 0) - 880; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(200, 0, 2, 0) - 889; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(201, 0, 2, 0) - 546; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(202, 0, 2, 0) - 551; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(203, 0, 2, 0) - 1109; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(204, 0, 2, 0) - 670; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(205, 0, 2, 0) - 917; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(206, 0, 2, 0) - 798; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(207, 0, 2, 0) - 713; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(208, 0, 2, 0) - 513; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(209, 0, 2, 0) - 574; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(210, 0, 2, 0) - 654; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(211, 0, 2, 0) - 498; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(212, 0, 2, 0) - 489; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(213, 0, 2, 0) - 270; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(214, 0, 2, 0) - 177; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(215, 0, 2, 0) - 219; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(216, 0, 2, 0) - 311; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(217, 0, 2, 0) - 357; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(218, 0, 2, 0) - 386; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(219, 0, 2, 0) - 487; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(220, 0, 2, 0) - 300; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(221, 0, 2, 0) - 303; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(222, 0, 2, 0) - 278; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(223, 0, 2, 0) - 429; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(224, 0, 2, 0) - 373; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(225, 0, 2, 0) - 360; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(226, 0, 2, 0) - 343; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(227, 0, 2, 0) - 272; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(228, 0, 2, 0) - 278; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(229, 0, 2, 0) - 243; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(230, 0, 2, 0) - 318; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(231, 0, 2, 0) - 317; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(232, 0, 2, 0) - 321; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(233, 0, 2, 0) - 310; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(234, 0, 2, 0) - 274; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(235, 0, 2, 0) - 319; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(236, 0, 2, 0) - 172; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(237, 0, 2, 0) - 220; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(238, 0, 2, 0) - 201; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(239, 0, 2, 0) - 204; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(240, 0, 2, 0) - 98; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(241, 0, 2, 0) - 89; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(242, 0, 2, 0) - 80; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(243, 0, 2, 0) - 121; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(244, 0, 2, 0) - 146; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(245, 0, 2, 0) - 212; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(246, 0, 2, 0) - 214; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(247, 0, 2, 0) - 212; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(248, 0, 2, 0) - 230; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    { double d = dyn.Obs(249, 0, 2, 0) - 188; ll += -0.5 * (d / x[7]) * (d / x[7]) - log(x[7] * sqrt(2 * M_PI)); }
    return ll;
}

bool CppObserver(Parameters& P, Randomizer& R, Reporter& dyn, double t, vector<double>& x)
{
    (void) P; (void) R; (void) dyn; (void) t;
    auto odds = [&](double x, double odds_ratio) {
        double a = x / (1 - x);
        return a * odds_ratio / (a * odds_ratio + 1);
    };
    auto asc = [&](double x, double y0, double y_lo, double s0, double s1) {
        double y1 = odds(y0, exp(y_lo));
        double xx = s0 + x * (s1 - s0);
        double h0 = exp(s0) / (1 + exp(s0));
        double h1 = exp(s1) / (1 + exp(s1));
        double h = (exp(xx) / (1 + exp(xx)) - h0) / (h1 - h0);
        return y0 + (y1 - y0) * h;
    };
    dyn.Obs(t, 0, 0, 0) = estimate_Rt(P, dyn, t, 0, 50);
    dyn.Obs(t, 0, 1, 0) = dyn("death_o", t, {}, {}) * asc((t - P.time0) / (258 - P.time0), x[3], x[4], -x[5], x[6]);
    dyn.Obs(t, 0, 2, 0) = dyn("cases_reported", t, {}, {}) * asc((t - P.time0) / (258 - P.time0), x[8], x[9], -x[10], x[11]);
    return true;
}
